version: '2.2'
services:
  web:
    build:
      context: .
      dockerfile: ToDo.Web/Dockerfile
    links:
      - db
  webng:
    build:
      context: ToDo.Web.Ng
  worker:
    build:
      context: .
      dockerfile: ToDo.Worker/Dockerfile
    links:
      - db
  db:
    image: 'mcr.microsoft.com/mssql/server:2017-latest-ubuntu'